service: braze-avro-converter

provider:
  name: aws
  runtime: python2.7
  profile: aws-profile
  region: us-east-1
  deploymentBucket: serverless-s3-bucket-name

functions:
  convert_avro:
    handler: convert_avro.main
    events:
      - s3:
        bucket: bucket-name
        event: s3:ObjectCreated:*
        rules:
          - prefix: buckt-prefix/
          - suffix: .avro
